//
// Created by tonym on 1/05/2020.
//

#ifndef POOII_TAREA_2_ENTREGA_01_05_CARLOSMERMA_FUNCIONES_H
#define POOII_TAREA_2_ENTREGA_01_05_CARLOSMERMA_FUNCIONES_H
#include "lib.h"
#include "CLASS/sistema.h"


#endif //POOII_TAREA_2_ENTREGA_01_05_CARLOSMERMA_FUNCIONES_H
